// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: sms/sms.proto

package sms

import (
	fmt "fmt"
	common "github.com/cargod-bj/b2c-proto-common/common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Sms service

func NewSmsEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Sms service

type SmsService interface {
	SendNormalSms(ctx context.Context, in *SmsDto, opts ...client.CallOption) (*common.Response, error)
	SendTempleteSms(ctx context.Context, in *SmsDto, opts ...client.CallOption) (*common.Response, error)
}

type smsService struct {
	c    client.Client
	name string
}

func NewSmsService(name string, c client.Client) SmsService {
	return &smsService{
		c:    c,
		name: name,
	}
}

func (c *smsService) SendNormalSms(ctx context.Context, in *SmsDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Sms.SendNormalSms", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsService) SendTempleteSms(ctx context.Context, in *SmsDto, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "Sms.SendTempleteSms", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sms service

type SmsHandler interface {
	SendNormalSms(context.Context, *SmsDto, *common.Response) error
	SendTempleteSms(context.Context, *SmsDto, *common.Response) error
}

func RegisterSmsHandler(s server.Server, hdlr SmsHandler, opts ...server.HandlerOption) error {
	type sms interface {
		SendNormalSms(ctx context.Context, in *SmsDto, out *common.Response) error
		SendTempleteSms(ctx context.Context, in *SmsDto, out *common.Response) error
	}
	type Sms struct {
		sms
	}
	h := &smsHandler{hdlr}
	return s.Handle(s.NewHandler(&Sms{h}, opts...))
}

type smsHandler struct {
	SmsHandler
}

func (h *smsHandler) SendNormalSms(ctx context.Context, in *SmsDto, out *common.Response) error {
	return h.SmsHandler.SendNormalSms(ctx, in, out)
}

func (h *smsHandler) SendTempleteSms(ctx context.Context, in *SmsDto, out *common.Response) error {
	return h.SmsHandler.SendTempleteSms(ctx, in, out)
}
